# koyeb.yml

name: telegram-webhook-bot
region: "fra1"  # Choose a region that suits you (e.g., fra1, sgp1, etc.)
services:
  - name: bot
    image: your_docker_image_name  # Use the image name (for example: username/telegram-webhook-bot)
    port: 8080
    env:
      API_ID: "<your_api_id>"
      API_HASH: "<your_api_hash>"
      BOT_TOKEN: "<your_bot_token>"
      MONGO_URI: "<your_mongo_uri>"
      WEBHOOK_URL: "<your_webhook_url>"
    plan: basic
    scale:
      count: 1
    health_check:
      path: "/health"
      protocol: "HTTP"
      port: 8080
    dockerfile: Dockerfile  # Path to your Dockerfile

# Optional: Add other services like MongoDB if using managed services
